-- 스키마 생성
create schema myworkspace;

-- 현재 쿼리창에서 사용할 스키마 선택
-- myworkspace 라는 스키마 공간에서 작업을 함.
-- 범위 지정, 안해주면, select * from myworkspace.photo;
-- 매번 점찍고 범위 지정해줘야함.
set schema 'myworkspace';

-- pk(primary key) : 주키
-- 유일성과 최소성을 보장하는 컬럼
-- 유일성: 전체 테이블 데이터에서 유일한 값을 가짐(사용자id, 이메일, 주민등록번호)
-- 최소성: 최소의 컬럼 개수와 크기로 구성되어있음
create table photo (
	-- 컬럼명 컬럼타입 [그외 옵션]
	-- generated by default as identity : 자동 증가되는 값 (1,2,3,4...)
	id int8 generated by default as identity, 
	created_time int8 not null, 
	-- description varchar(255) : 가변길이 문자열 255 바이트
	description varchar(255), 
	file_name varchar(255), 
	file_type varchar(255), 
	photo_url TEXT, 
	title varchar(255), 
	primary key (id)
)

--(CREATE)
-- 데이터를 1건 추가 
-- insert into 테이블명(컬럼1, 컬럼2...) values(값1, 값2...)
insert into photo(created_time, title, description)
-- > 데이터 추가
values(1, 'test', 'DBeaver');


--(READ)
-- select 컬럼목록 from 테이블명; *는 전체
-- 테이블 데이터를 전체 조회
select * from photo;
-- 특정 컬럼(세로칸)만 조회
select id, title from photo;
-- photo 테이블 전체 목록 조회
select 
	id, 
	created_time, 
	description, 
	file_name, 
	file_type, 
	photo_url, 
	title 
from photo;


truncate table photo;


-- (UPDATE)
update photo set 
	created_time=1, 
	description='새로운 설명', 
	file_name='파일명', 
	file_type='...', 
	photo_url='...', 
	title='새로운제목' 
where id=5;







--(DELETE)
-- 특정 데이터 삭제
-- **** where 조건이 없으면 전체 데이터가 삭제됨, 조심할 것
delete from photo where id = 16;



--//===== contact =======================================


--(CREATE)
insert into contact (created_time, email, memo, "name" , phone) 
values (1, 'dbeaver@gmail.com', 'dbeaver', 'dbeaver', '000-0000-0000');




--(READ)
select * from contact;

select
	id, 
	created_time,
	email,
	memo,
	"name",
	phone
from contact;

select "name" from contact;




-- (UPDATE)
update contact set
	created_time=2,
	email='DDD@naver.com',
	memo='UPDATE',
	"name"='UPDATE',
	phone='xxx-xxxx-xxxx'
where id = 3;




--(DELETE)
-- **** where 조건이 없으면 전체 데이터가 삭제됨, 조심할 것
delete from contact where id = 7;

