# yml (yaml, 야믈 (야멀))
# 시스템 설정에 사용하는 파일

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # jdbc - java databse connector
    # :postgresql - 데이터베이스 엔진
    # //url (//database-1.caip~) - 데이터베이스 주소 url
    # :5432 - 데이터베이스 접속 포트
    # /postgres - 접속할 데이터베이스(이름)
    # jdbc를 이용해 postgresql포트의 데이터베이스로 접속한다
    url: jdbc:postgresql://database-1.caipcwydwewo.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=myworkspace
    username: postgres
    password: password123!  #기본 접속정보 넣음
  jpa:
    show-sql: true
    generate-ddl: true
    