const CovidData = [
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "강원",
    gubunEn: "Gangwon-do",
    overFlowCnt: "0",
    localOccCnt: "29",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "검역",
    gubunEn: "Lazaretto",
    overFlowCnt: "13",
    localOccCnt: "0",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "경기",
    gubunEn: "Gyeonggi-do",
    overFlowCnt: "5",
    localOccCnt: "851",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "경남",
    gubunEn: "Gyeongsangnam-do",
    overFlowCnt: "1",
    localOccCnt: "95",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "경북",
    gubunEn: "Gyeongsangbuk-do",
    overFlowCnt: "1",
    localOccCnt: "54",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "광주",
    gubunEn: "Gwangju",
    overFlowCnt: "0",
    localOccCnt: "13",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "대구",
    gubunEn: "Daegu",
    overFlowCnt: "0",
    localOccCnt: "46",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "대전",
    gubunEn: "Daejeon",
    overFlowCnt: "1",
    localOccCnt: "29",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "부산",
    gubunEn: "Busan",
    overFlowCnt: "0",
    localOccCnt: "49",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "서울",
    gubunEn: "Seoul",
    overFlowCnt: "4",
    localOccCnt: "833",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "세종",
    gubunEn: "Sejong",
    overFlowCnt: "0",
    localOccCnt: "11",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "울산",
    gubunEn: "Ulsan",
    overFlowCnt: "0",
    localOccCnt: "14",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "인천",
    gubunEn: "Incheon",
    overFlowCnt: "2",
    localOccCnt: "198",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "전남",
    gubunEn: "Jeollanam-do",
    overFlowCnt: "0",
    localOccCnt: "18",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "전북",
    gubunEn: "Jeollabuk-do",
    overFlowCnt: "0",
    localOccCnt: "24",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "제주",
    gubunEn: "Jeju",
    overFlowCnt: "0",
    localOccCnt: "10",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "충남",
    gubunEn: "Chungcheongnam-do",
    overFlowCnt: "0",
    localOccCnt: "52",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "충북",
    gubunEn: "Chungcheongbuk-do",
    overFlowCnt: "0",
    localOccCnt: "74",
  },
  {
    stdDay: "2021년 10월 07일 00시",
    gubun: "합계",
    gubunEn: "Total",
    overFlowCnt: "27",
    localOccCnt: "2400",
  },
];

export default CovidData;
